
export const homePageConstants = {
    GET_SOME_COMPANIES_REQUEST : "GET_SOME_COMPANIES_REQUEST",
    GET_SOME_COMPANIES_SUCCESS : "GET_SOME_COMPANIES_SUCCESS",
    GET_SOME_COMPANIES_FAILURE : "GET_SOME_COMPANIES_FAILURE",


    
};