
export const commentConstants = {
    GET_ALL_COMMENTS_REQUEST : "GET_ALL_COMMENTS_REQUEST",
    GET_ALL_COMMENTS_SUCCESS : "GET_ALL_COMMENTS_SUCCESS",
    GET_ALL_COMMENTS_FAILURE : "GET_ALL_COMMENTS_FAILURE",


    ADD_COMMENT_REQUEST: "ADD_COMMENT_REQUEST",
    ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
    ADD_COMMENT_FAILURE : "ADD_COMMENT_FAILURE",

    DELETE_COMMENT_REQUEST: "DELETE_COMMENT_REQUEST",
    DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
    DELETE_COMMENT_FAILURE : "DELETE_COMMENT_FAILURE",

    CHANGE_COMMENT_STATE_REQUEST : "CHANGE_COMMENT_STATE_REQUEST",
    CHANGE_COMMENT_STATE_SUCCESS : "CHANGE_COMMENT_STATE_SUCCESS",
    CHANGE_COMMENT_STATE_FAILURE : "CHANGE_COMMENT_STATE_FAILURE",

    UPDATE_COMMENT_REQUEST : "UPDATE_COMMENT_REQUEST",
    UPDATE_COMMENT_SUCCESS : "UPDATE_COMMENT_SUCCESS",
    UPDATE_COMMENT_FAILURE : "UPDATE_COMMENT_FAILURE"
};