export const newsConstants = {
    CANCEL_EDITING : "CANCEL_EDITING_NEWS",
    START_EDITING : "START_EDITING_NEWS",
    CONFIRM_EDITING : "CONFIRM_EDITING_NEWS",
    DELETE_NEW_POST : "DELETED_NEW_POST"
};
