export const postConstants = {
    CANCEL_EDITING : "CANCEL_EDITING_POST",


    START_EDITING : "START_EDITING_POST",


    CONFIRM_EDITING : "CONFIRM_EDITING_POST",

    ADD_REQUEST : "POST_ADDED_REQUEST",
    ADD_SUCCESS : "POST_ADDED_SUCCESS",
    ADD_FAILURE : "POST_ADDED_FAILURE",

    UPDATE_REQUEST : "POST_UPDATED_REQUEST",
    UPDATE_SUCCESS : "POST_UPDATED_SUCCESS",
    UPDATE_FAILURE : "POST_UPDATED_FAILURE",


    GET_ALL_POSTS_REQUEST : "GET_ALL_POSTS_REQUEST",
    GET_ALL_POSTS_SUCCESS: "GET_ALL_POSTS_SUCCESS",
    GET_ALL_POSTS_FAILURE : "GET_ALL_POSTS_FAILURE",


    DELETE_NEW_POST : "DELETED_NEW_POST"


};
