export const GET_CAMPAIGN_SUCCESS = 'GET_CAMPAIGN_SUCCESS';
export const GET_CAMPAIGN = 'GET_CAMPAIGN';
export const GET_CAMPAIGN_FAIL = 'GET_CAMPAIGN_FAIL';
export const CHANGE_RATING_SUCCESS = 'CHANGE_RATING_SUCCESS';
export const CHANGE_RATING = 'CHANGE_RATING';
export const CHANGE_RATING_FAIL = 'CHANGE_RATING_FAIL';

export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';
export const DELETE_CAMPAIGN_SUCCESS = 'DELETE_CAMPAIGN_SUCCESS';
export const DELETE_CAMPAIGN_FAIL = 'DELETE_CAMPAIGN_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const RESET_DELETING = 'RESET_DELETING';


export const DONATE= 'DONATE';
export const DONATE_SUCCESS = 'DONATE_SUCCESS';
export const DONATE_FAIL = 'DONATE_FAIL';

export const GET_REWARD= 'GET_REWARD';
export const GET_REWARD_SUCCESS = 'GET_REWARD_SUCCESS';
export const GET_REWARD_FAIL = 'GET_REWARD_FAIL';
