
export const companiesListConstants = {
    GET_COMPANIES_BY_CATEGORY_REQUEST : "GET_COMPANIES_BY_CATEGORY_REQUEST",
    GET_COMPANIES_BY_CATEGORY_SUCCESS : "GET_COMPANIES_BY_CATEGORY_SUCCESS",
    GET_COMPANIES_BY_CATEGORY_FAILURE : "GET_COMPANIES_BY_CATEGORY_FAILURE",


    
};